apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "simple-python-website.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "simple-python-website.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis

